### ISSUE TITLE
Word change, but conceptual: Changing "Mint" to something else for the button to mint reserves.

### ISSUE THREAD

**Issue by mejango** [jbx-protocol/juicehouse#21]
"change the "mint" to something else? might just be because it's a NFT project, but a lot of people in Tiles are clicking that button without understanding what it does" - @peripheralist 

I think "Distribute" would be a stronger word, I also think moving the button right next to the field would help associate the button to the field instead of having it all the way across the row.

![image](https://user-images.githubusercontent.com/77952627/126231207-48ce1711-b23d-491f-9b39-b35e80bfaa39.png)

**Comment by nervetrip** [comment]
I like `Distribute` as well. I'd propose that we separate this into **YOUR TOKENS** and **NETWORK TOKENS** sections. Sections would be placed either left/right of each other or above/below, but I'm leaning toward left/right.

- The YOUR section would have info and actions that only affect your own wallet. 
- The NETWORK section would have actions that may affect other wallets in the network, even though it might include you as well.

Open to feedback and ideas @peripheralist @mejango

**Comment by mejango** [comment]
I like this idea

**Comment by mejango** [comment]
I also think we could try putting the "Reserved" row in the purple box beneath the "Withdraw" row. Both of these actions are public actions.

**Comment by mejango** [comment]
^^ and they're both affected by the current funding cycle configuration.

**Comment by peripheralist** [comment]
> I like `Distribute` as well. I'd propose that we separate this into **YOUR TOKENS** and **NETWORK TOKENS** sections. Sections would be placed either left/right of each other or above/below, but I'm leaning toward left/right.
> 
> * The YOUR section would have info and actions that only affect your own wallet.
> * The NETWORK section would have actions that may affect other wallets in the network, even though it might include you as well.
> 
> Open to feedback and ideas @peripheralist @mejango

Can't quite imagine how this would work, but I'd love to see a draft of it

In the meantime I think changing Mint -> Distribute would be a big win

**Comment by nervetrip** [comment]
With the recent changes made to the UI, can we close this? I think the rearranging of things on the page basically accomplishes what I was proposing with a "your" and "network" section.

**Comment by mejango** [comment]
yep
