### ISSUE TITLE
Add details to the modal that appears when "redeem is clicked"

### ISSUE THREAD

**Issue by mejango** [jbx-protocol/juicehouse#22]
"add some more info to the "redeem" screen that makes the effect of the current bonding curve clearer, and explicitly states that your tokens will be burned" - @peripheralist 

I'd also love to see the amount that I can redeem for somewhere on the Dashboard (or at least in the modal). Right now I have to open the modal, and click "Max" to see the amount (img 3)

![image](https://user-images.githubusercontent.com/77952627/126231279-d5a48f20-987c-4ced-a60d-fd760512acf0.png)

![image](https://user-images.githubusercontent.com/77952627/126231305-276f094e-1db5-4bfb-8b7d-a3462f94d992.png)

![image](https://user-images.githubusercontent.com/77952627/126231379-d53ea530-99b5-4463-a1cc-48b0ad8c404d.png)

**Comment by peripheralist** [comment]
thanks for issuifying this 😄 also agree with the redeem amount. something like "your tokens are worth X ETH if redeemed now" could be orienting
