### ISSUE TITLE
UI Dangling 0

### ISSUE THREAD

**Issue by mejango** [jbx-protocol/juicehouse#23]
maybe:
0 in your wallet
23741241 staked

the dangling 0 feels weird
![image](https://user-images.githubusercontent.com/77952627/126246160-893e7be5-00f0-454e-b04a-c7d25317d608.png)

**Comment by mejango** [comment]
I think it looks great when there is a number other than 0 tho 
![image](https://user-images.githubusercontent.com/77952627/126259747-78553fa2-227f-43e4-b14c-13064fbefd7d.png)

**Comment by peripheralist** [comment]
this is good possible design improvement to track, i don't love the dangling 0 either. but this does feel like the least confusing layout we've had so far, so i'm happy to keep this until someone has a better layout in mind

**Comment by peripheralist** [comment]
> When it's 0, just make it "0 in your wallet"

I like this 👍

**Comment by mejango** [comment]
Can this be closed? I think its fixed.

**Comment by mejango** [comment]
This was fixed.
