### ISSUE TITLE
Date string format change

### ISSUE THREAD

**Issue by mejango** [jbx-protocol/juicehouse#25]
Make the events date be "3 hours ago" etc, instead of "7-19-21 7:50pm"

![image](https://user-images.githubusercontent.com/77952627/126255486-e5a28601-55c4-4289-a92f-b5d10a90bc92.png)

**Comment by nervetrip** [comment]
Also, when actual dates are shown, they should be shown in a more global format, such as YYYY-MM-DD.

**Comment by mejango** [comment]
agree
