### ISSUE TITLE
Verify contracts on Etherscan

### ISSUE THREAD

**Issue by mejango** [jbx-protocol/juicehouse#26]

**Comment by bonkrat** [comment]
Found a useful hardhat plugin for this: https://hardhat.org/plugins/nomiclabs-hardhat-etherscan.html

You could set it up as part of the `deploy.js` script to verify the script post deploy. You could probably throw the deployed addresses into a text file and run through them as well, but for now I just ran this command through manually from each of the deployed addresses (from the pin in the Discord dev channel):

`npx hardhat verify --network mainnet DEPLOYED_CONTRACT_ADDRESS "Constructor argument 1"`

And here's the results!

Successfully verified contract Active7DaysFundingCycleBallot on Etherscan.
https://etherscan.io/address/0xEf7480b6E7CEd228fFB0854fe49A428F562a8982#code

Successfully verified contract FundingCycles on Etherscan.
https://etherscan.io/address/0xf507B2A1dD7439201eb07F11E1d62AfB29216e2E#code

Successfully verified contract Governance on Etherscan.
https://etherscan.io/address/0xAc43e14c018490D045a774008648c701cda8C6b3#code

Successfully verified contract ModStore on Etherscan.
https://etherscan.io/address/0xB9E4B658298C7A36BdF4C2832042A5D6700c3Ab8#code

Successfully verified contract OperatorStore on Etherscan.
https://etherscan.io/address/0xab47304D987390E27Ce3BC0fA4Fe31E3A98B0db2#code

Successfully verified contract Prices on Etherscan.
https://etherscan.io/address/0xa9537Cc42555564206D4E57c0eb6943d56E83A30#code

Successfully verified contract Projects on Etherscan.
https://etherscan.io/address/0x9b5a4053FfBB11cA9cd858AAEE43cc95ab435418#code

Successfully verified contract TerminalDirectory on Etherscan.
https://etherscan.io/address/0x46C9999A2EDCD5aA177ed7E8af90c68b7d75Ba46#code

Successfully verified contract TerminalV1 on Etherscan.
https://etherscan.io/address/0xd569D3CCE55b71a8a3f3C418c329A66e5f714431#code

**Comment by mejango** [comment]
sweet.
