### ISSUE TITLE
Mint/Distribute reserved tokens modal

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juicehouse#27]
Related to #21 

Regardless of the word used on the button, a confirmation modal that shows how the reserved tickets will be distributed would be helpful in clarifying its purpose, and probably prevent people from paying the gas for this without realizing what they're doing

**Comment by mejango** [comment]
This isn't a big deal in the lates UI. But still nice to have.

**Comment by peripheralist** [comment]
done
