### ISSUE TITLE
Add the default payout to the project owner to this section

### ISSUE THREAD

**Issue by mejango** [jbx-protocol/juicehouse#33]
![image](https://user-images.githubusercontent.com/77952627/126518723-d59c8bbc-58e5-4142-8103-098ba5134a42.png)

this should say 100% to the project owner's address.

**Comment by peripheralist** [comment]
done

**Comment by mejango** [comment]
Kinda. What'd be most intuitive is to fill out the rest of the percentage and say it belongs to the owner.
In the screenshot above, itd say `"0x1234....5678" (owners address)          100%`

In this screenshot, it would have a row at the end that says `"0x1234....5678" (owners address) "       39.9%`
![image](https://user-images.githubusercontent.com/77952627/126907936-67ecc25c-5452-490b-8af8-67a999f44e8e.png)

**Comment by peripheralist** [comment]
good idea

**Comment by mejango** [comment]
check this comment also https://github.com/jbx-protocol/juicehouse/issues/33#issuecomment-886233734
