### ISSUE TITLE
funding cycle history does not load

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juicehouse#39]
shows "no past funding cycles"

**Comment by bonkrat** [comment]
I think the issue surfaces here:

https://github.com/jbx-protocol/juicehouse/blob/cf98ad8ff966cb6e14622ab7a541fe4b1c563ce3/packages/app/src/components/Dashboard/FundingCycles.tsx#L122

where there is no `previous` property set for `fundingCycle`.

**Comment by peripheralist** [comment]
thanks @bonkrat !
