### ISSUE TITLE
Setting no funding target yields max int $$$

### ISSUE THREAD

**Issue by teddywilson** [jbx-protocol/juicehouse#41]
<img width="565" alt="Screen Shot 2021-07-25 at 4 46 19 PM" src="https://user-images.githubusercontent.com/10104111/126913029-7c977a69-d720-476c-8cb7-01c93cf6a19b.png">

**Comment by bonkrat** [comment]
Took a quick peek at this one today, it looks like it's defaulting to the max value here:

https://github.com/jbx-protocol/juicehouse/blob/main/packages/app/src/components/Create/BudgetForm.tsx#L57

This makes sense as you don't want a cap on your funding.  In the case where there's no funding limit should the dollar value just be hidden or display something along the lines of "No limit"?

https://github.com/jbx-protocol/juicehouse/blob/main/packages/app/src/components/Dashboard/PayoutModsList.tsx#L147-L156

**Comment by mejango** [comment]
Yep, exactly. I think just "100%" would be strong.
