### ISSUE TITLE
Can't add/edit project description. 

### ISSUE THREAD

**Issue by 0xNMillion** [jbx-protocol/juicehouse#50]
I did add a great description but for some reason it didn't save. Went to add it again and not an option in the setting button. @peripheralist 
<img width="627" alt="Screen Shot 2021-08-01 at 10 42 59 PM" src="https://user-images.githubusercontent.com/87771041/127797718-1ce87ec1-7630-4c67-9943-9468b73f60ac.png">

**Comment by peripheralist** [comment]
😨 not sure how this flew under our radar for so long. thanks for pointing it out. expect a fix soon

**Comment by 0xNMillion** [comment]
tight tight

**Comment by peripheralist** [comment]
fixed
