### ISSUE TITLE
A better way to know if the Distribute button has been hit on Reserve Tokens

### ISSUE THREAD

**Issue by 0xNMillion** [jbx-protocol/juicehouse#66]
<img width="517" alt="Screen Shot 2021-08-11 at 7 42 14 AM" src="https://user-images.githubusercontent.com/87771041/129023164-17b25b0b-a1ad-458b-83f6-507de3d96022.png">
I always thought the amount of tokens at the bottom were Undistributed waiting to [Distribute]

**Comment by peripheralist** [comment]
that's right—that number will go to 0 after it's been distributed
