### ISSUE TITLE
s/Ticket(s)/{Token} in frontend

### ISSUE THREAD

**Issue by odd-amphora** [jbx-protocol/juicehouse#76]
Showing the ticker symbol instead of "Tickets" is probably more direct as to what's happening behind the scenes. It looks like we do this in some places, but not in others. Maybe it's worth offering some more consistency.

<img width="819" alt="Screen_Shot_2021-08-16_at_9 14 34_AM" src="https://user-images.githubusercontent.com/88144767/129570088-56b81900-88e2-4160-b984-82cf3ce8c913.png">

**Comment by peripheralist** [comment]
fixed
